# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kelvin C. Silva
tagline:          'Software and Systems Engineer'
description:      'I am a generalist Software'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Kelvin C. Silva'
  url:            https://linkedin.com/in/kelvinsilva747

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
